from pathlib import Path
import sys


PROJECT_ROOT = Path(__file__).resolve().parent.parent
PYTHON_BIN = sys.executable
PACKAGE_ROOT = "launcher/packages/seaman_suite"
APP_ENV_KEY = "launcher-app"
APP_ENV_LABEL = "Launcher App"
APP_ENV_REQUIREMENTS = str(PROJECT_ROOT / "launcher" / "requirements.app.txt")
FRIDA_ENV_KEY = "launcher-frida"
FRIDA_ENV_LABEL = "Launcher + Frida"
FRIDA_ENV_REQUIREMENTS = str(PROJECT_ROOT / "launcher" / "requirements.frida.txt")


def python_task(
    task_id: str,
    label: str,
    group: str,
    script_path: str,
    *,
    args: list[str] | None = None,
    description: str,
    kind: str = "oneshot",
    requires_admin: bool = False,
    available: bool = True,
    open_url: str | None = None,
    launch_mode: str = "background",
    has_interface: bool = False,
    interface_key: str | None = None,
    interface_label: str | None = None,
    interface_mode: str = "generic",
    conflicts_with: list[str] | None = None,
    venv_key: str | None = None,
    venv_label: str | None = None,
    venv_requirements: str | None = None,
    venv_packages: list[str] | None = None,
    can_stop: bool = True,
    stop_label: str | None = None,
    no_start: bool = False,
) -> dict:
    return {
        "id": task_id,
        "label": label,
        "group": group,
        "runner": "python",
        "script_path": script_path,
        "args": args or [],
        "description": description,
        "kind": kind,
        "requires_admin": requires_admin,
        "available": available,
        "open_url": open_url,
        "launch_mode": launch_mode,
        "has_interface": has_interface,
        "interface_key": interface_key or task_id,
        "interface_label": interface_label or label,
        "interface_mode": interface_mode,
        "conflicts_with": conflicts_with or [],
        "venv_key": venv_key,
        "venv_label": venv_label or venv_key,
        "venv_requirements": venv_requirements,
        "venv_packages": venv_packages or [],
        "can_stop": can_stop,
        "stop_label": stop_label or "Stop",
        "no_start": no_start,
    }


def package_path(*parts: str) -> str:
    return "/".join((PACKAGE_ROOT, *parts))


TASKS = [
    python_task(
        "launch_game",
        "Run Game",
        "main",
        "launcher/scripts/run_game.py",
        description="Launches the configured Seaman executable from the shared launcher settings.",
        kind="service",
        interface_label="Game",
        stop_label="Stop Game",
    ),
    python_task(
        "menu_translation_v24",
        "Menu Translation Hook",
        "main",
        package_path("menu_translation", "run_menu_translate_v25.py"),
        description="Attaches the Frida menu translation hook and keeps it alive while the process runs.",
        kind="service",
        launch_mode="detached",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
    ),
    python_task(
        "build_stage_exes",
        "Build Stage EXEs",
        "installation",
        package_path("exe_builder", "build_stages.py"),
        description="Builds Seaman_Stage1_Baby.exe, Stage3_Child.exe, Stage5_Adult.exe, and Stage8_Frog.exe from the clean original Seaman.exe. Set the 'Original Seaman.exe' path in Settings first.",
        kind="oneshot",
        launch_mode="console",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
        can_stop=False,
    ),
    python_task(
        "surgical_patcher_workspace",
        "Surgical Patcher",
        "installation",
        package_path("patcher", "run_patcher.py"),
        description="Patch and revert individual DLLs. Shows install status for each patch and supports apply-all / revert-all.",
        kind="service",
        open_url="http://127.0.0.1:5005/",
        has_interface=True,
        interface_key="patcher",
        interface_label="Patcher",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "force_persistent_office",
        "Force Persistent Office",
        "installation",
        package_path("force_persistent_apps", "force_persistent_office.py"),
        description="Runs the persistence helper that spoofs Windows state to keep background services alive.",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
    ),
    python_task(
        "ftp_redirect_v3",
        "FTP Redirect Hook",
        "servers",
        package_path("ftp_redirect", "run_ftp_redirect_v3.py"),
        description="The game calls InternetConnectA(\"www.seamail.tv\", port 21, irumote/muratamang) for updates. Hooks that call via Frida and redirects it to 127.0.0.1 — start Dual HTTP+FTP Server first, then attach this while the game is running.",
        kind="service",
        launch_mode="console",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
        can_stop=False,
    ),
    python_task(
        "smtp_pop_server",
        "SMTP + POP Server",
        "servers",
        package_path("smtp_and_pop_server", "managed_mail_server.py"),
        description="Restores the SeaMail SMTP and POP stack using the standard service implementation.",
        kind="service",
        launch_mode="console",
        has_interface=True,
        interface_key="mail",
        interface_label="Mail",
        interface_mode="custom",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "smtp_pop_server_debug",
        "SMTP + POP Debug Server",
        "servers",
        package_path("smtp_and_pop_server", "managed_mail_server_debug.py"),
        description="Win11-friendly debug variant using shifted ports 1100 and 2525.",
        kind="service",
        launch_mode="console",
        has_interface=True,
        interface_key="mail",
        interface_label="Mail",
        interface_mode="custom",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "dual_http_ftp_server",
        "Dual HTTP + FTP Server",
        "servers",
        package_path("ftp_server", "dual_server.py"),
        description="Runs the legacy HTTP and FTP services together for file updates and web requests.",
        kind="service",
        open_url="http://127.0.0.1/",
        conflicts_with=["weather_redirection_server"],
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "weather_redirection_server",
        "Weather Redirection Server",
        "servers",
        package_path("weather_http_server_on_80", "weather_mock.py"),
        description="Spoofs the JMA weather endpoint so in-game weather can be controlled locally.",
        kind="service",
        requires_admin=True,
        conflicts_with=["dual_http_ftp_server"],
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "variable_tracker_dashboard",
        "GEM Variable Tracker Dashboard",
        "tools",
        package_path("seaman_variable_tracker", "app.py"),
        description="NOTE THAT YOU NEED TO RUN THE CREATURE TRACKER ENGINE FOR THIS TO WORK. Flask and Socket.IO dashboard for live variable polling and display.",
        kind="service",
        launch_mode="detached",
        open_url="http://127.0.0.1:5081/",
        has_interface=True,
        interface_label="Variable Tracker",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "creature_tracker_engine",
        "Creature Tracker Engine",
        "tools",
        package_path("seaman_variable_tracker", "scripts", "creature_tracker.py"),
        description="Memory polling engine that feeds the GEM variable tracker dashboard.",
        kind="service",
        launch_mode="detached",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
    ),
    python_task(
        "comparison_monitor",
        "SDP Comparison Monitor",
        "tools",
        package_path("comparison_outpt", "monitor_sdp_comparisons_v8.py"),
        description="Utility monitor for comparing and watching SDP output changes.",
        kind="service",
        launch_mode="console",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
    ),
    {"id": "_sep_tools_overlays", "group": "tools", "runner": "separator"},
    python_task(
        "screensaver_overlay",
        "Interactive Screensaver Overlay",
        "tools",
        package_path("cli_screensaver_menu", "screensaver_overlay_v7.py"),
        description="Old, cli, version of the screensaver shower. More features, but no menu overlay. I suggest using Menu Replacement Overlay instead",
        kind="service",
        launch_mode="detached",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
    ),
    python_task(
        "menu_overlay_fullscreen",
        "Menu Overlay (Fullscreen)",
        "main",
        package_path("menu_replacement", "menu_overlay_v14.py"),
        args=["--fullscreen"],
        description="Menu overlay for borderless fullscreen / screensaver mode — no title bar on the game window.",
        kind="service",
        launch_mode="detached",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
    ),
    python_task(
        "menu_overlay_replacement",
        "Menu Replacement Overlay",
        "main",
        package_path("menu_replacement", "menu_overlay_v14.py"),
        description="Alternative overlay layer for translated and direct menu interaction.",
        kind="service",
        launch_mode="detached",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
    ),
    python_task(
        "position_tracker_bridge",
        "3D Position Tracker Bridge",
        "tools",
        package_path("position_tracker_bridge", "bridge8_1.py"),
        description="Tkinter visualizer — listens on UDP 8888 for 736-byte packets (100 floats + 84 DWORDs). Needs a sender: on Win11 use 'Position Tracker Win11 Sender' below; on XP use xp_debug_tracker_v8.1.exe (source + build scripts in frida_xp/).",
        kind="service",
        has_interface=True,
        interface_label="Position Bridge",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "position_tracker_win11_sender",
        "Position Tracker Win11 Sender",
        "tools",
        package_path("position_tracker_bridge", "win11_sender.py"),
        description="Frida hook that reads Seaman.exe memory and sends 736-byte UDP packets to the bridge on localhost:8888. Win11 replacement for xp_debug_tracker_v8.1.exe.",
        kind="service",
        launch_mode="console",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
    ),
    python_task(
        "open_xp_tracker_folder",
        "Open XP Tracker Build Folder",
        "tools",
        "launcher/scripts/open_xp_tracker_folder.py",
        description="Opens the xp_build folder in Explorer — contains xp_debug_tracker_v8.1.exe (run on XP), xp_debug_tracker_v8.1.cpp (source), and BUILD_TRACKER_V8.1.bat (build script for XP).",
        kind="oneshot",
        launch_mode="background",
        can_stop=False,
        no_start=True,
        open_url=(PROJECT_ROOT / "launcher" / "packages" / "seaman_suite" / "position_tracker_bridge" / "xp_build").as_uri(),
    ),
    python_task(
        "db_manager_v2",
        "DB Manager V2",
        "db",
        package_path("db_manager_main", "app_v2.py"),
        description="Premium Flask database editor with change tracking, refresh controls, and inline editing.",
        kind="service",
        open_url="http://127.0.0.1:5074/",
        has_interface=True,
        interface_label="DB Manager V2",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "db_manager_v1",
        "DB Manager V1",
        "db",
        package_path("db_manager_main", "app.py"),
        description="Original Flask database editor UI for the Seaman, User, and Calendar databases.",
        kind="service",
        open_url="http://127.0.0.1:5073/",
        has_interface=True,
        interface_label="DB Manager V1",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "db_proxy_web_analyzer",
        "DB Proxy Web Analyzer",
        "db",
        package_path("db_manager_proxy", "web_analyzer.py"),
        description="Web dashboard for live database call analysis.",
        kind="service",
        open_url="http://127.0.0.1:5075/",
        has_interface=True,
        interface_label="DB Proxy Web",
        conflicts_with=["db_proxy_monitor"],
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "db_proxy_monitor",
        "DB Proxy Monitor",
        "db",
        package_path("db_manager_proxy", "db_monitor.py"),
        description="UDP monitor for internal database traffic and variable discovery.",
        kind="service",
        has_interface=True,
        interface_label="DB Proxy Monitor",
        conflicts_with=["db_proxy_web_analyzer"],
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "fix_loop_v33",
        "Fix Loop / Interaction Hook v33",
        "fixes",
        package_path("fix_loop", "run_fix_v33.py"),
        description="Frida hook that fixes the interaction loop. Interactive console — vocab, pick, spoof, status, discover commands. Required for Adult and Frog stages — without it the interaction loop stalls.",
        kind="service",
        launch_mode="console",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
        can_stop=False,
    ),
    python_task(
        "dna_selector",
        "DNA Selector",
        "db",
        package_path("dna_selector", "dna_app.py"),
        description="14×14 trait matrix picker. Click a cell to set Element 1 + Element 2, apply to Seaman.udb. Includes random picker.",
        kind="service",
        open_url="http://127.0.0.1:5076/",
        has_interface=True,
        interface_key="dna",
        interface_label="DNA",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
    python_task(
        "launch_tools_wt",
        "Tools in Tabs (Windows Terminal)",
        "suggested",
        "launcher/scripts/launch_tools_wt.py",
        description="Opens Menu Overlay, Translation Hook, SDP Monitor, and Fix Loop hook as four tabs in a single Windows Terminal window.",
        kind="oneshot",
        launch_mode="background",
        venv_key=FRIDA_ENV_KEY,
        venv_label=FRIDA_ENV_LABEL,
        venv_requirements=FRIDA_ENV_REQUIREMENTS,
        can_stop=False,
    ),
    python_task(
        "db_quickdb_server",
        "Quick DB Editor",
        "db",
        package_path("db_manager_quickdb", "edit_db.py"),
        description="Command-line UDB editor for direct key search and editing. It now resolves shared parser imports from the sibling DB tool folders.",
        kind="oneshot",
        launch_mode="console",
        interface_label="Quick DB",
        venv_key=APP_ENV_KEY,
        venv_label=APP_ENV_LABEL,
        venv_requirements=APP_ENV_REQUIREMENTS,
    ),
]


def task_map() -> dict[str, dict]:
    return {task["id"]: task for task in TASKS if task.get("runner") != "separator"}


def group_tasks() -> dict[str, list[dict]]:
    groups = {"installation": [], "main": [], "suggested": [], "fixes": [], "servers": [], "settings": [], "docs": [], "tools": [], "db": []}
    for task in TASKS:
        groups.setdefault(task["group"], []).append(task)
    return groups
